spring:
  profiles:
    include: datasource
  lifecycle:
    timeout-pre-shutdown-phase: 20s
  application:
    name: api-server
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 80
  shutdown: graceful
  tomcat:
    max-http-form-post-size: 8MB
    uri-encoding: UTF-8
    connection-timeout: 10s
    max-swallow-size: 8MB
  servlet:
    encoding:
      charset: UTF-8
      force: true
  max-http-request-header-size: 80KB
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    property:
      prefix: ENC(
      suffix: )
springdoc:
  packages-to-scan: com.sample.api
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: demo-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true
decorator:
  datasource:
    p6spy:
      enable-logging: true
logging:
  config: classpath:log4j2.xml
